### ISSUE TITLE
Can not install the indicator on Linux Ubuntu 20

### ISSUE THREAD

**Issue by renepardon** [derkomai/NordIndicator#8]
This is the error I receive:

```
╭─ ~/Projekte/Github/NordIndicator │ main ▓▒░──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────░▒▓ ✔ │ DE nord │ 11:50:21 
╰─ python3 NordIndicator.py install
Traceback (most recent call last):
  File "NordIndicator.py", line 9, in <module>
    require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
```

python3 --version               
**Python 3.8.10**

**Comment by Spitfireap** [comment]
hey ! 
can you try `sudo apt-get install python3-gi` and then try again please ? :D 
if this doesn't work, try `sudo pip3 install pgi`

**Comment by renepardon** [comment]
It's already installed and the latest version ;(
Edit: so both doesn't work

**Comment by renepardon** [comment]
@Spitfireap On another Github project I found the solution:

```bash
sudo apt install gir1.2-appindicator3-0.1
```

This way it works and starts immediately.
